/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package rpc.thrift.file.transfer;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.15.0)", date = "2021-09-26")
public enum ResResult implements org.apache.thrift.TEnum {
  FILE_START(0),
  FILE_PARAM_VALIDATION_FAIL(1),
  SUCCESS(2),
  TOKEN_FAILED(3),
  FILE_BROKEN(4),
  FILE_END(5);

  private final int value;

  private ResResult(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ResResult findByValue(int value) { 
    switch (value) {
      case 0:
        return FILE_START;
      case 1:
        return FILE_PARAM_VALIDATION_FAIL;
      case 2:
        return SUCCESS;
      case 3:
        return TOKEN_FAILED;
      case 4:
        return FILE_BROKEN;
      case 5:
        return FILE_END;
      default:
        return null;
    }
  }
}
